version: '3.8'

services:
  ge-ia-platform:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    restart: unless-stopped
    
    # Configurações de saúde
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    # Configurações de recursos (ajuste conforme necessário)
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M